<?php
/**
 * SimoneChinaglia Custom Carrier Trackers Extension
 *
 * @category     SimoneChinaglia
 * @package      SimoneChinaglia_CustomCarrierTrackers
 * @author       Simone Chinaglia
 * @copyright    Copyright (c) 2022 SimoneChinaglia (https://www.simonechinaglia.com)
 * @license      LICENSE_MV.txt or https://www.simonechinaglia.com/license-agreement/
 */
?>
<?php /* @var \Magento\Framework\View\Element\Template $block */ ?>
<?php $_shipment = $block->getShipment() ?>
<?php
/* @var \Magento\Sales\Model\Order $_order */
$_order = $block->getOrder() ?>
<?php if ($_shipment && $_order): ?>
    <?php $trackCollection = $_shipment->getTracksCollection() ?>
    <?php if ($trackCollection): ?>
        <br />
        <table class="shipment-track">
            <thead>
            <tr>
                <th><?= $block->escapeHtml(__('Shipped By')) ?></th>
                <th><?= $block->escapeHtml(__('Tracking Number')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($trackCollection as $_item): ?>
                <tr>
                    <td><?= $block->escapeHtml($_item->getTitle()) ?>:</td>
                    <?php $trackingUrl = $this->helper(\SimoneChinaglia\CustomCarrierTrackers\Helper\Data::class)->getTrackingUrl(
                        $_item->getCarrierCode(),
                        $_item->getNumber(),
                        $_shipment->getId()
                    )?>
                    <?php if ($trackingUrl): ?>
                        <td><a href="<?= $trackingUrl; ?>"><?= $block->escapeHtml($_item->getNumber()) ?></a></td>
                    <?php else: ?>
                        <td>
                            <a href="<?= $block->escapeUrl($block->getTrackingUrl()->getUrl($_item)) ?>" target="_blank">
                                <?= $block->escapeHtml($_item->getNumber()) ?>
                            </a>
                        </td>
                    <?php endif; ?>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    <?php endif; ?>
<?php endif; ?>
